[libraries]
gradleup-shadow = "com.gradleup.shadow:shadow-gradle-plugin:9.2.2"
intellij-platform = "org.jetbrains.intellij.platform:org.jetbrains.intellij.platform.gradle.plugin:2.10.5"

# same as in https://github.com/GradleUp/shadow/blob/main/gradle/libs.versions.toml
apache-ant = "org.apache.ant:ant:1.10.15"